# 你的cookie, 获取方式请参考附加说明
cookie_string: x
# 版面ID (784 = 二跑)
fid: 784
# 主题ID 需替换成你的帖子
tid: -1
# 发帖内容文件
content_file: content.txt
# 分割两个回帖的分割行内容
split: '### SPLIT ###'
# 发帖频率配置, 通过注释保留1个. 参考 https://tools.fun/crontab.html
cron: '* * * * *' # 每分钟
# cron: '*/30 * * * *' # 每30分钟(00,30)
# cron: '0 * * * *' # 每整点
# cron: '0 */4 * * *' # 每4小时的整点(0,4,8,12,16,20)
# cron: '30 8,12,20 * * *' # 每天的8:30 12:30 20:30
# cron: '0 * */2 * *' # 隔天每整点
